from morphobase.assays.smoke import SmokeAssay
from morphobase.assays.identity import IdentityAssay
from morphobase.assays.wound_closure import WoundClosureAssay
from morphobase.assays.stress_recruitment import StressRecruitmentAssay
from morphobase.assays.growth_usefulness import GrowthUsefulnessAssay
from morphobase.assays.gridworld_remap import GridworldRemapAssay
from morphobase.assays.lesion_gridworld_remap import LesionGridworldRemapAssay
from morphobase.assays.compensation_block import CompensationBlockAssay
from morphobase.assays.lesion_sequential_rules import LesionSequentialRulesAssay
from morphobase.assays.lesion_split_mnist import LesionSplitMNISTAssay
from morphobase.assays.sequential_rules import SequentialRulesAssay
from morphobase.assays.plasticity_stress import PlasticityStressAssay
from morphobase.assays.setpoint_rewrite import SetpointRewriteAssay
from morphobase.assays.stigmergic_highway_probe import StigmergicHighwayProbeAssay
from morphobase.assays.lightcone import LightconeAssay
from morphobase.assays.lesion_battery import LesionBatteryAssay
from morphobase.assays.lesion_preserves_competence import LesionPreservesCompetenceAssay
from morphobase.assays.oscillatory_coupling_probe import OscillatoryCouplingProbeAssay
from morphobase.assays.reaction_diffusion_probe import ReactionDiffusionProbeAssay
from morphobase.assays.tissue_field_probe import TissueFieldProbeAssay
from morphobase.assays.mnist_sanity import MNISTSanityAssay
from morphobase.assays.permuted_fashion_mnist import PermutedFashionMNISTAssay
from morphobase.assays.permuted_mnist import PermutedMNISTAssay
from morphobase.assays.port_remap import PortRemapAssay
from morphobase.assays.predictive_coding_probe import PredictiveCodingProbeAssay
from morphobase.assays.split_fashion_mnist import SplitFashionMNISTAssay
from morphobase.assays.split_mnist import SplitMNISTAssay
ASSAYS = {'smoke': SmokeAssay, 'identity': IdentityAssay, 'wound_closure': WoundClosureAssay, 'stress_recruitment': StressRecruitmentAssay, 'growth_usefulness': GrowthUsefulnessAssay, 'gridworld_remap': GridworldRemapAssay, 'lesion_gridworld_remap': LesionGridworldRemapAssay, 'compensation_block': CompensationBlockAssay, 'sequential_rules': SequentialRulesAssay, 'lesion_sequential_rules': LesionSequentialRulesAssay, 'lesion_split_mnist': LesionSplitMNISTAssay, 'plasticity_stress': PlasticityStressAssay, 'setpoint_rewrite': SetpointRewriteAssay, 'lightcone': LightconeAssay, 'lesion_battery': LesionBatteryAssay, 'lesion_preserves_competence': LesionPreservesCompetenceAssay, 'tissue_field_probe': TissueFieldProbeAssay, 'oscillatory_coupling_probe': OscillatoryCouplingProbeAssay, 'reaction_diffusion_probe': ReactionDiffusionProbeAssay, 'stigmergic_highway_probe': StigmergicHighwayProbeAssay, 'predictive_coding_probe': PredictiveCodingProbeAssay, 'mnist_sanity': MNISTSanityAssay, 'split_mnist': SplitMNISTAssay, 'split_fashion_mnist': SplitFashionMNISTAssay, 'permuted_mnist': PermutedMNISTAssay, 'permuted_fashion_mnist': PermutedFashionMNISTAssay, 'port_remap': PortRemapAssay}
